- hosts: localhost
  connection: local
  become: true  # Require root privileges

  tasks:
    - include_vars: ansible-vars.yaml

    - name: Update package lists
      apt: update_cache=yes

    - name: Install dependencies
      apt:
        name:
          - helm
          - apt-transport-https
          - curl
          - conntrack
          - docker.io

    - name: Install kubectl
      ansible.builtin.get_url:
        url: "{{ kubectl_url }}"
        dest: /usr/bin/kubectl
        mode: "755"
       
    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0755

    - name: Start Minikube cluster
      command: minikube start --driver=docker --force

    - name: Deploy Helm Chart
      helm:
        name: readfiles-app
        chart: readfiles-app
        namespace: sb
